/**
 * QuestionFeedback Component
 *
 * This component renders a text field for entering feedback on a specific question.
 * It supports AI-generated feedback detection and styling, and allows integration
 * with a shared context to programmatically update feedback fields from a parent component.
 *
 * Props:
 * - questionId (string): ID of the question (used for tracking and registry).
 * - feedback (string): The current feedback text to show.
 * - onChange (function): Callback to update feedback (called with questionId and new text).
 * - placeholder (string): Optional placeholder text for the input field.
 * - updateKey (string): Used to force update effect when feedback content changes externally.
 *
 * Features:
 * - Shows "AI Feedback" chip if the feedback was generated by AI.
 * - Uses React.memo with custom comparison to avoid unnecessary re-renders.
 * - Registers and unregisters each feedback field using a context (FeedbackFieldsContext)
 *   so that other parts of the app can programmatically set feedback values.
 */

import React, { useRef, useEffect, useContext } from "react";
import PropTypes from "prop-types";
import { Box, Typography, TextField, Chip, useTheme } from "@mui/material";
import AutoFixHighIcon from "@mui/icons-material/AutoFixHigh";
import FeedbackFieldsContext from "./FeedbackFieldsContext";

const QuestionFeedback = React.memo(
	function QuestionFeedback({
		questionId,
		feedback = "",
		onChange = () => {},
		placeholder = "Provide specific feedback on this answer...",
		updateKey = "",
	}) {
		const theme = useTheme();

		// Check if feedback is AI-generated
		const isAIGenerated =
			typeof feedback === "string" && feedback.includes("You");

		// Use a ref to directly update the DOM element
		const textareaRef = useRef(null);

		// Access the feedback fields registry
		const feedbackFieldsRegistry = useContext(FeedbackFieldsContext);

		// Register this feedback field in the context for direct access
		useEffect(() => {
			if (textareaRef.current && questionId) {
				// Register this field
				feedbackFieldsRegistry.registerField(questionId, {
					setFeedback: (text) => {
						if (textareaRef.current) {
							textareaRef.current.value = text;

							// Trigger React's onChange handlers
							const event = new Event("input", { bubbles: true });
							textareaRef.current.dispatchEvent(event);
						}
					},
				});

				return () => {
					// Cleanup on unmount
					feedbackFieldsRegistry.unregisterField(questionId);
				};
			}
		}, [questionId, feedbackFieldsRegistry]);

		// Effect to update the textarea value directly when feedback changes
		useEffect(() => {
			if (textareaRef.current && feedback) {
				// Directly set the value property on the DOM element
				textareaRef.current.value = feedback;

				// Create events to notify React about the change
				const inputEvent = new Event("input", { bubbles: true });
				textareaRef.current.dispatchEvent(inputEvent);
			}
		}, [feedback, questionId, updateKey]);

		return (
			<Box sx={{ flex: 1 }}>
				<Typography
					variant="subtitle2"
					gutterBottom
					component="div"
					sx={{
						display: "flex",
						alignItems: "center",
						gap: 0.5,
						color: theme.palette.text.secondary,
					}}
				>
					Question Feedback
					{isAIGenerated && (
						<Chip
							size="small"
							icon={<AutoFixHighIcon fontSize="small" />}
							label="AI Feedback"
							color="secondary"
							sx={{
								ml: 1,
								backgroundColor: theme.palette.secondary.main,
								color: theme.palette.secondary.contrastText,
								fontWeight: "bold",
							}}
						/>
					)}
				</Typography>
				<TextField
					multiline
					rows={2}
					size="small"
					fullWidth
					value={feedback}
					onChange={(e) => onChange && onChange(questionId, e.target.value)}
					placeholder={placeholder}
					inputProps={{
						"data-question-id": questionId,
					}}
					InputProps={{
						sx: {
							bgcolor: isAIGenerated
								? theme.palette.secondary.main + "1A"
								: "transparent",
							"& .MuiOutlinedInput-notchedOutline": {
								borderColor: isAIGenerated
									? theme.palette.secondary.main
									: undefined,
								borderWidth: isAIGenerated ? "1px" : undefined,
							},
						},
					}}
					inputRef={textareaRef}
				/>
				<Typography
					variant="caption"
					color="text.secondary"
					sx={{ mt: 0.5, display: "block" }}
				>
					This feedback will be shown to the student for this specific question.
				</Typography>
			</Box>
		);
	},
	// Memoization comparison function
	(prevProps, nextProps) => {
		// Return true if props haven't changed (to prevent re-render)
		return (
			prevProps.feedback === nextProps.feedback &&
			prevProps.updateKey === nextProps.updateKey &&
			prevProps.questionId === nextProps.questionId
		);
	}
);

// Add prop types validation
QuestionFeedback.propTypes = {
	questionId: PropTypes.string,
	feedback: PropTypes.string,
	onChange: PropTypes.func,
	placeholder: PropTypes.string,
	updateKey: PropTypes.string,
};

export default QuestionFeedback;
